# Generated by Django 5.2 on 2025-05-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='c_activities.activity')),
            ],
        ),
    ]
